/**
 * @file function0.hpp
 * @author wladt
 * @date Dec 5, 2013
 */

#ifndef __PFS_BITS_FUNCTION0_HPP__
#define __PFS_BITS_FUNCTION0_HPP__

#undef PFS_FUNCTION_ARGS_NUM
#define PFS_FUNCTION_ARGS_NUM 0
/*
#define PFS_FUNCTION_TEMPLATE_PARMS
#define PFS_FUNCTION_TEMPLATE_ARGS
#define PFS_FUNCTION_PARMS
#define PFS_FUNCTION_ARGS
#define PFS_FUNCTION_MEMBER_TEMPLATE_ARGS
#define PFS_FUNCTION_MEMBER_TEMPLATE_PARMS
#define PFS_FUNCTION_MEMBER_PARMS
#define PFS_FUNCTION_MEMBER_ARGS
*/
#include "function_template.hpp"

#endif /* __PFS_BITS_FUNCTION0_HPP__ */
