/*
 * typelist.hpp
 * AUTOMATICALLY GENERATED BY 'typelist.pl'
 *
 *  Created on: 2015-04-05 14:11:37
 *      Author: wladt
 *  
 */

#ifndef __PFS_BITS_TYPELIST_HPP__
#define __PFS_BITS_TYPELIST_HPP__

//
// see http://collaboration.cmc.ec.gc.ca/science/rpn/biblio/ddj/Website/articles/CUJ/2002/cexp2002/alexandr/alexandr.htm
//

//#if __cplusplus >= 201103L // C++11
//# error You are using C++11 compliant compiler.
//# error Use variadic templates to implement 'cons' struct.
//#endif

namespace pfs {

template <typename Head, typename Tail>
struct typelist
{
	typedef Head head;
	typedef Tail tail;
};

struct null_typelist {};

template <class T1
	, typename T2
	, typename T3
	, typename T4
	, typename T5
	, typename T6
	, typename T7
	, typename T8
	, typename T9
	, typename T10
	, typename T11
	, typename T12
	, typename T13
	, typename T14
	, typename T15
	, typename T16
	, typename T17
	, typename T18
	, typename T19
	, typename T20
	, typename T21
	, typename T22
	, typename T23
	, typename T24
	, typename T25
	, typename T26
	, typename T27
	, typename T28
	, typename T29
	, typename T30
	, typename T31
	, typename T32
	, typename T33
	, typename T34
	, typename T35
	, typename T36
	, typename T37
	, typename T38
	, typename T39
	, typename T40
	, typename T41
	, typename T42
	, typename T43
	, typename T44
	, typename T45
	, typename T46
	, typename T47
	, typename T48
	, typename T49
	, typename T50>
struct cons
{	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39
		, typelist<T40
		, typelist<T41
		, typelist<T42
		, typelist<T43
		, typelist<T44
		, typelist<T45
		, typelist<T46
		, typelist<T47
		, typelist<T48
		, typelist<T49
		, typelist<T50, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1>
struct cons <T1
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1, null_typelist>
	type;
};

template <typename T1, typename T2>
struct cons <T1
	, T2
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2, null_typelist>
	> type;
};

template <typename T1, typename T2, typename T3>
struct cons <T1
	, T2
	, T3
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3, null_typelist>
	> > type;
};

template <typename T1, typename T2, typename T3, typename T4>
struct cons <T1
	, T2
	, T3
	, T4
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4, null_typelist>
	> > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5, null_typelist>
	> > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6, null_typelist>
	> > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7, null_typelist>
	> > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8, null_typelist>
	> > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9, null_typelist>
	> > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10, null_typelist>
	> > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11, null_typelist>
	> > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12, null_typelist>
	> > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13, null_typelist>
	> > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14, null_typelist>
	> > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15, null_typelist>
	> > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16, null_typelist>
	> > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17, null_typelist>
	> > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18, null_typelist>
	> > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19, null_typelist>
	> > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20, null_typelist>
	> > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21, null_typelist>
	> > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38, typename T39>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, T39
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38, typename T39, typename T40>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, T39
	, T40
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39
		, typelist<T40, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38, typename T39, typename T40, typename T41>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, T39
	, T40
	, T41
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39
		, typelist<T40
		, typelist<T41, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38, typename T39, typename T40, typename T41, typename T42>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, T39
	, T40
	, T41
	, T42
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39
		, typelist<T40
		, typelist<T41
		, typelist<T42, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38, typename T39, typename T40, typename T41, typename T42, typename T43>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, T39
	, T40
	, T41
	, T42
	, T43
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39
		, typelist<T40
		, typelist<T41
		, typelist<T42
		, typelist<T43, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38, typename T39, typename T40, typename T41, typename T42, typename T43, typename T44>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, T39
	, T40
	, T41
	, T42
	, T43
	, T44
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39
		, typelist<T40
		, typelist<T41
		, typelist<T42
		, typelist<T43
		, typelist<T44, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38, typename T39, typename T40, typename T41, typename T42, typename T43, typename T44, typename T45>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, T39
	, T40
	, T41
	, T42
	, T43
	, T44
	, T45
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39
		, typelist<T40
		, typelist<T41
		, typelist<T42
		, typelist<T43
		, typelist<T44
		, typelist<T45, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38, typename T39, typename T40, typename T41, typename T42, typename T43, typename T44, typename T45, typename T46>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, T39
	, T40
	, T41
	, T42
	, T43
	, T44
	, T45
	, T46
	, null_typelist
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39
		, typelist<T40
		, typelist<T41
		, typelist<T42
		, typelist<T43
		, typelist<T44
		, typelist<T45
		, typelist<T46, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38, typename T39, typename T40, typename T41, typename T42, typename T43, typename T44, typename T45, typename T46, typename T47>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, T39
	, T40
	, T41
	, T42
	, T43
	, T44
	, T45
	, T46
	, T47
	, null_typelist
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39
		, typelist<T40
		, typelist<T41
		, typelist<T42
		, typelist<T43
		, typelist<T44
		, typelist<T45
		, typelist<T46
		, typelist<T47, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38, typename T39, typename T40, typename T41, typename T42, typename T43, typename T44, typename T45, typename T46, typename T47, typename T48>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, T39
	, T40
	, T41
	, T42
	, T43
	, T44
	, T45
	, T46
	, T47
	, T48
	, null_typelist
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39
		, typelist<T40
		, typelist<T41
		, typelist<T42
		, typelist<T43
		, typelist<T44
		, typelist<T45
		, typelist<T46
		, typelist<T47
		, typelist<T48, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31, typename T32, typename T33, typename T34, typename T35, typename T36, typename T37, typename T38, typename T39, typename T40, typename T41, typename T42, typename T43, typename T44, typename T45, typename T46, typename T47, typename T48, typename T49>
struct cons <T1
	, T2
	, T3
	, T4
	, T5
	, T6
	, T7
	, T8
	, T9
	, T10
	, T11
	, T12
	, T13
	, T14
	, T15
	, T16
	, T17
	, T18
	, T19
	, T20
	, T21
	, T22
	, T23
	, T24
	, T25
	, T26
	, T27
	, T28
	, T29
	, T30
	, T31
	, T32
	, T33
	, T34
	, T35
	, T36
	, T37
	, T38
	, T39
	, T40
	, T41
	, T42
	, T43
	, T44
	, T45
	, T46
	, T47
	, T48
	, T49
	, null_typelist>
{
	typedef typelist<T1
		, typelist<T2
		, typelist<T3
		, typelist<T4
		, typelist<T5
		, typelist<T6
		, typelist<T7
		, typelist<T8
		, typelist<T9
		, typelist<T10
		, typelist<T11
		, typelist<T12
		, typelist<T13
		, typelist<T14
		, typelist<T15
		, typelist<T16
		, typelist<T17
		, typelist<T18
		, typelist<T19
		, typelist<T20
		, typelist<T21
		, typelist<T22
		, typelist<T23
		, typelist<T24
		, typelist<T25
		, typelist<T26
		, typelist<T27
		, typelist<T28
		, typelist<T29
		, typelist<T30
		, typelist<T31
		, typelist<T32
		, typelist<T33
		, typelist<T34
		, typelist<T35
		, typelist<T36
		, typelist<T37
		, typelist<T38
		, typelist<T39
		, typelist<T40
		, typelist<T41
		, typelist<T42
		, typelist<T43
		, typelist<T44
		, typelist<T45
		, typelist<T46
		, typelist<T47
		, typelist<T48
		, typelist<T49, null_typelist>
	> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > type;
};

template <class TypeList> struct typelist_max_size;

template <>
struct typelist_max_size<null_typelist>
{
    enum { result = 0 };
};

template <typename Head, typename Tail>
struct typelist_max_size<typelist<Head, Tail> >
{
private:
    enum { tailResult = size_t(typelist_max_size<Tail>::result) };
public:
    enum { result = sizeof(Head) > tailResult
        ? sizeof(Head)
        : size_t(tailResult)
    };
};

} // pfs

#endif /* __PFS_BITS_TYPELIST_HPP__ */
