#ifndef __CWT_ASCII_H__
#define __CWT_ASCII_H__

#define ASCII_CHAR_NULL                      0x00 /* NUL */
#define ASCII_CHAR_START_OF_HEADING          0x01 /* SOH */
#define ASCII_CHAR_START_OF_TEXT             0x02 /* STX */
#define ASCII_CHAR_END_OF_TEXT               0x03 /* ETX */
#define ASCII_CHAR_END_OF_TRANSMISSION       0x04 /* EOT */
#define ASCII_CHAR_ENQUIRY                   0x05 /* ENQ */
#define ASCII_CHAR_ACKNOWLEDGE               0x06 /* ACK */
#define ASCII_CHAR_BELL                      0x07 /* BEL (Beep) */
#define ASCII_CHAR_BACKSPACE                 0x08 /* BS */
#define ASCII_CHAR_HORIZONTAL_TAB            0x09 /* HT */
#define ASCII_CHAR_LINE_FEED                 0x0A /* LF */ 
#define ASCII_CHAR_VERTICAL_TAB              0x0B /* VT */
#define ASCII_CHAR_FORM_FEED                 0x0C /* FF */
#define ASCII_CHAR_CARRIAGE_RETURN           0x0D /* CR */
#define ASCII_CHAR_SHIFT_OUT                 0x0E /* SO */
#define ASCII_CHAR_SHIFT_IN                  0x0F /* SI */
#define ASCII_CHAR_DATA_LINK_ESCAPE          0x10 /* DLE */
#define ASCII_CHAR_DEVICE_CONTROL_1          0x11 /* DC1 (XON) */
#define ASCII_CHAR_DEVICE_CONTROL_2          0x12 /* DC2 */
#define ASCII_CHAR_DEVICE_CONTROL_3          0x13 /* DC3 (XOFF) */
#define ASCII_CHAR_DEVICE_CONTROL_4          0x14 /* DC4 */
#define ASCII_CHAR_NEGATIVE_ACKNOWLEDGE      0x15 /* NAK */
#define ASCII_CHAR_SYNCHRONOUS_IDLE          0x15 /* SYN */
#define ASCII_CHAR_END_OF_TRANSMISSION_BLOCK 0x17 /* ETB */
#define ASCII_CHAR_CANCEL                    0x18 /* CAN */
#define ASCII_CHAR_END_OF_MEDIUM             0x19 /* EM */
#define ASCII_CHAR_SUBSTITUTE                0x1A /* SUB */
#define ASCII_CHAR_ESCAPE                    0x1B /* ESC */
#define ASCII_CHAR_FILE_SEPARATOR            0x1C /* FS */
#define ASCII_CHAR_GROUP_SEPARATOR           0x1D /* GS */
#define ASCII_CHAR_RECORD_SEPARATOR          0x1E /* RS */
#define ASCII_CHAR_UNIT_SEPARATOR            0x1F /* US */
#define ASCII_CHAR_SPACE                     0x20

#define ASCII_CHAR_EXCLAMATION_MARK          0x21
#define ASCII_CHAR_QUOTATION_MARK            0x22
#define ASCII_CHAR_NUMBER_SIGN               0x23
#define ASCII_CHAR_DOLLAR_SIGN               0x24
#define ASCII_CHAR_PERCENT_SIGN              0x25
#define ASCII_CHAR_AMPERSAND                 0x26
#define ASCII_CHAR_APOSTROPHE                0x27
#define ASCII_CHAR_LEFT_PARENTHESIS          0x28
#define ASCII_CHAR_RIGHT_PARENTHESIS         0x29
#define ASCII_CHAR_ASTERISK                  0x2A
#define ASCII_CHAR_PLUS_SIGN                 0x2B
#define ASCII_CHAR_COMMA                     0x2C
#define ASCII_CHAR_HYPHEN                    0x2D /* MINUS SIGN */
#define ASCII_CHAR_PERIOD                    0x2E /* FULL STOP */
#define ASCII_CHAR_SLASH                     0x2F /* SOLIDUS */
#define ASCII_CHAR_DIGIT_ZERO                0x30
#define ASCII_CHAR_DIGIT_ONE                 0x31
#define ASCII_CHAR_DIGIT_TWO                 0x32
#define ASCII_CHAR_DIGIT_THREE               0x33
#define ASCII_CHAR_DIGIT_FOUR                0x34
#define ASCII_CHAR_DIGIT_FIVE                0x35
#define ASCII_CHAR_DIGIT_SIX                 0x36
#define ASCII_CHAR_DIGIT_SEVEN               0x37
#define ASCII_CHAR_DIGIT_EIGHT               0x38
#define ASCII_CHAR_DIGIT_NINE                0x39
#define ASCII_CHAR_COLON                     0x3A
#define ASCII_CHAR_SEMICOLON                 0x3B
#define ASCII_CHAR_LESS_SIGN                 0x3C /* LESS-THAN SIGN, LEFT_ANGLE_BRACKET */
#define ASCII_CHAR_EQUALS_SIGN               0x3D
#define ASCII_CHAR_GREATER_SIGN              0x3E /* GREATER-THAN SIGN, RIGHT ANGLE BRACKET */
#define ASCII_CHAR_QUESTION_MARK             0x3F
#define ASCII_CHAR_COMMERCIAL_AT_SIGN        0x40

#define ASCII_CHAR_LATIN_CAPITAL_LETTER_A    0x41
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_B    0x42
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_C    0x43
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_D    0x44
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_E    0x45
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_F    0x46
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_G    0x47
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_H    0x48
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_I    0x49
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_J    0x4A
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_K    0x4B
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_L    0x4C
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_M    0x4D
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_N    0x4E
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_O    0x4F
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_P    0x50
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_Q    0x51
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_R    0x52
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_S    0x53
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_T    0x54
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_U    0x55
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_V    0x56
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_W    0x57
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_X    0x58
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_Y    0x59
#define ASCII_CHAR_LATIN_CAPITAL_LETTER_Z    0x5A

#define ASCII_CHAR_LATIN_SMALL_LETTER_A      0x61
#define ASCII_CHAR_LATIN_SMALL_LETTER_B      0x62
#define ASCII_CHAR_LATIN_SMALL_LETTER_C      0x63
#define ASCII_CHAR_LATIN_SMALL_LETTER_D      0x64
#define ASCII_CHAR_LATIN_SMALL_LETTER_E      0x65
#define ASCII_CHAR_LATIN_SMALL_LETTER_F      0x66
#define ASCII_CHAR_LATIN_SMALL_LETTER_G      0x67
#define ASCII_CHAR_LATIN_SMALL_LETTER_H      0x68
#define ASCII_CHAR_LATIN_SMALL_LETTER_I      0x69
#define ASCII_CHAR_LATIN_SMALL_LETTER_J      0x6A
#define ASCII_CHAR_LATIN_SMALL_LETTER_K      0x6B
#define ASCII_CHAR_LATIN_SMALL_LETTER_L      0x6C
#define ASCII_CHAR_LATIN_SMALL_LETTER_M      0x6D
#define ASCII_CHAR_LATIN_SMALL_LETTER_N      0x6E
#define ASCII_CHAR_LATIN_SMALL_LETTER_O      0x6F
#define ASCII_CHAR_LATIN_SMALL_LETTER_P      0x70
#define ASCII_CHAR_LATIN_SMALL_LETTER_Q      0x71
#define ASCII_CHAR_LATIN_SMALL_LETTER_R      0x72
#define ASCII_CHAR_LATIN_SMALL_LETTER_S      0x73
#define ASCII_CHAR_LATIN_SMALL_LETTER_T      0x74
#define ASCII_CHAR_LATIN_SMALL_LETTER_U      0x75
#define ASCII_CHAR_LATIN_SMALL_LETTER_V      0x76
#define ASCII_CHAR_LATIN_SMALL_LETTER_W      0x77
#define ASCII_CHAR_LATIN_SMALL_LETTER_X      0x78
#define ASCII_CHAR_LATIN_SMALL_LETTER_Y      0x79
#define ASCII_CHAR_LATIN_SMALL_LETTER_Z      0x7A

#define ASCII_CHAR_DELETE                    0x7F

/* CP866 cyrillic characters */
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_A  			0x80
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_BE 			0x81
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_VE 			0x82
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_GHE 			0x83
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_DE 			0x84
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_IE 			0x85
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_ZHE 			0x86
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_ZE 			0x87
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_I 			0x88
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_SHORT_I 		0x89
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_KA 			0x8A
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_EL 			0x8B
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_EM 			0x8C
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_EN 			0x8D
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_O 			0x8E
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_PE 			0x8F
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_ER 			0x90
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_ES 			0x91
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_TE 			0x92
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_U 			0x93
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_EF 			0x94
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_HA 			0x95
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_TSE 			0x96
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_CHE 			0x97
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_SHA 			0x98
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_SHCHA 		0x99
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_HARD_SIGN 	0x9A
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_YERU 		0x9B
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_SOFT_SIGN 	0x9C
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_E 			0x9D
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_YU 			0x9E
#define CP866_CHAR_CYRILLIC_CAPITAL_LETTER_YA 			0x9F

#define CP866_CHAR_CYRILLIC_SMALL_LETTER_A  		0xA0
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_BE 		0xA1
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_VE 		0xA2
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_GHE 		0xA3
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_DE 		0xA4
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_IE 		0xA5
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_ZHE 		0xA6
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_ZE 		0xA7
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_I 			0xA8
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_SHORT_I 	0xA9
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_KA 		0xAA
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_EL 		0xAB
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_EM 		0xAC
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_EN 		0xAD
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_O 			0xAE
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_PE 		0xAF
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_ER 		0xE0
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_ES 		0xE1
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_TE 		0xE2
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_U 			0xE3
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_EF 		0xE4
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_HA 		0xE5
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_TSE 		0xE6
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_CHE 		0xE7
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_SHA 		0xE8
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_SHCHA 		0xE9
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_HARD_SIGN 	0xEA
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_YERU 		0xEB
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_SOFT_SIGN 	0xEC
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_E 			0xED
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_YU 		0xEE
#define CP866_CHAR_CYRILLIC_SMALL_LETTER_YA 		0xEF

#endif /* __CWT_ASCII_H__ */
